name: ci
on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: "0 2 * * 0-6"
jobs:
  
  tests:
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    runs-on: ${{ matrix.os }}
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run test suite
      env:
        TICKTICK_USER: ${{ secrets.TICKTICK_USER }}
        TICKTICK_PASS: ${{ secrets.TICKTICK_PASS }}
      run: |
        pytest 
        
  documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python runtime
        uses: actions/setup-python@v1
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Deploy documentation
        run: |
          mkdocs gh-deploy --force
