name: ci
on:
  push:
  pull_request:
    branches:
      - master
      - main
  schedule:
    - cron: "0 2 * * 0-6"
jobs:
  
  # We have to declare the jobs separately since sync issues can occur failing the test suite if multiple
  # suites are running at the same time.
  test-ubuntu-3_6:
    
    runs-on: ubuntu_latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run test suite
      env:
        TICKTICK_USER: ${{ secrets.TICKTICK_USER }}
        TICKTICK_PASS: ${{ secrets.TICKTICK_PASS }}
      run: |
        pytest 
        
  test-ubuntu-3_7:
    
    runs-on: ubuntu_latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run test suite
      env:
        TICKTICK_USER: ${{ secrets.TICKTICK_USER }}
        TICKTICK_PASS: ${{ secrets.TICKTICK_PASS }}
      run: |
        pytest 
        
  test-ubuntu-3_8:

    runs-on: ubuntu_latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run test suite
      env:
        TICKTICK_USER: ${{ secrets.TICKTICK_USER }}
        TICKTICK_PASS: ${{ secrets.TICKTICK_PASS }}
      run: |
        pytest
        
  test-ubuntu-3_9:

    runs-on: ubuntu_latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run test suite
      env:
        TICKTICK_USER: ${{ secrets.TICKTICK_USER }}
        TICKTICK_PASS: ${{ secrets.TICKTICK_PASS }}
      run: |
        pytest
        
  test-ubuntu-3_x:

    runs-on: ubuntu_latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run test suite
      env:
        TICKTICK_USER: ${{ secrets.TICKTICK_USER }}
        TICKTICK_PASS: ${{ secrets.TICKTICK_PASS }}
      run: |
        pytest
        
    
